"""Add is_anonymous column in Reply table

Revision ID: 4c0a294a73ff
Revises: 
Create Date: 2024-04-29 21:38:11.759807

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4c0a294a73ff"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("reply", sa.Column("is_anonymous", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("reply") as batch_op:
        batch_op.drop_column("is_anonymous")
    # ### end Alembic commands ###
