"""Add back is_anonymous column.

Revision ID: 9dd55346f94c
Revises: 67c25a1466bf
Create Date: 2024-04-29 18:10:55.094081

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9dd55346f94c"
down_revision = "67c25a1466bf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("reply", schema=None) as batch_op:
        batch_op.drop_column("is_anonymous")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("reply", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_anonymous", sa.BOOLEAN()))

    # ### end Alembic commands ###
