"""Add anonymous reply column

Revision ID: ad214955cdee
Revises: 
Create Date: 2024-04-29 17:51:42.558679

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ad214955cdee"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("reply", schema=None) as batch_op:
        batch_op.drop_column("is_anonymous")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("reply", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_anonymous", sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
