"""Add LikePost and LikeReply tables

Revision ID: cc89798449b5
Revises: 5d2396cc94db
Create Date: 2024-05-08 20:39:15.408586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc89798449b5'
down_revision = '5d2396cc94db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('likes', sa.Integer(), nullable=True))
    op.add_column('reply', sa.Column('likes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reply', 'likes')
    op.drop_column('post', 'likes')
    # ### end Alembic commands ###
