name: Auto Request Review & Notify Discord

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
    request-reviewers:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v2
    
          - name: Auto Request Review
            uses: necojackarc/auto-request-review@v0.13.0
            with:
              token: ${{ secrets.ACTIONS }}
              config: .github/auto-request-review.yml
    send-discord-message:
        runs-on: ubuntu-latest
        steps:
          - name: Send message to Discord
            run: |
              curl -H "Content-Type: application/json" \
                   -d '{"content": ":rotating_light: A new pull request is ready for review: ${{ github.event.pull_request.html_url }} :rotating_light: "}' \
                   "https://discord.com/api/webhooks/1221708396684775464/hum7U_0ffADT6dAaSQJMd9uQSqj3LwH5zto_1iH1yx5mNxazk1h_zcdYjrpK9xDGlg1N"
        

